"""Tests for the pure pieces of scripts/export_digest.py.

Only render_digest and rank_without_user are tested here — they're pure
(no DB access). All database assembly lives in export_digest.main(), which
mirrors the untested-by-design precedent set by scripts/seed_demo.py.

Fakes use the plain Event(...) constructor (not Event.model_construct — that
bypasses SQLAlchemy's instance-state setup for SQLModel table models and
breaks attribute access entirely). Plain construction never touches the
database; it only becomes a DB write once you session.add()/commit() it.
"""
from __future__ import annotations

import inspect
from datetime import datetime, timedelta, timezone
from decimal import Decimal

from app.models.event import Event
from app.services.recommender import ScoredEvent
from scripts.export_digest import rank_without_user, render_digest

UTC = timezone.utc


def _make_event(
    *,
    id: int,
    title: str,
    start_at: datetime,
    created_at: datetime,
    venue_name: str | None = "The Chapel",
    external_url: str | None = "https://example.com/e",
    tags: list[str] | None = None,
    price: Decimal | None = None,
    is_free: bool = False,
) -> Event:
    return Event(
        id=id,
        title=title,
        start_at=start_at,
        created_at=created_at,
        source_name="ticketmaster",
        source_tier=1,
        location="SRID=4326;POINT(0 0)",
        venue_name=venue_name,
        external_url=external_url,
        tags=tags or [],
        categories=[],
        price=price,
        currency="USD" if price is not None else None,
        is_free=is_free,
        status="scheduled",
    )


def _scored(event: Event, *, matched_tags: list[str] | None = None) -> ScoredEvent:
    return ScoredEvent(
        event=event,
        total_score=50.0,
        vibe_score=0.0,
        popularity_score=0.0,
        freshness_score=0.0,
        matched_tags=matched_tags or [],
    )


# ---------------------------------------------------------------------------
# render_digest
# ---------------------------------------------------------------------------


def test_render_digest_header_and_window_line() -> None:
    generated_at = datetime(2026, 7, 11, 9, 0, tzinfo=UTC)
    out = render_digest([], generated_at, 7)

    lines = out.splitlines()
    assert lines[0] == "# Events digest — 2026-07-11"
    assert lines[1] == (
        "_Window: next 7 days · generated by truth-of-fun · regenerate: make digest_"
    )


def test_render_digest_one_line_per_event_up_to_top() -> None:
    generated_at = datetime(2026, 7, 11, 9, 0, tzinfo=UTC)
    events = [
        _scored(
            _make_event(
                id=i,
                title=f"Event {i}",
                start_at=generated_at + timedelta(days=1, hours=i),
                created_at=generated_at,
            )
        )
        for i in range(5)
    ]

    out = render_digest(events, generated_at, 7, top=3)

    event_lines = [line for line in out.splitlines() if line.startswith("- ")]
    assert len(event_lines) == 3
    assert "Event 0" in event_lines[0]
    assert "Event 2" in event_lines[2]


def test_render_digest_empty_scored_list_says_no_events() -> None:
    generated_at = datetime(2026, 7, 11, 9, 0, tzinfo=UTC)
    out = render_digest([], generated_at, 7)

    assert "_No events found in this window._" in out
    assert not any(line.startswith("- ") for line in out.splitlines())


def test_render_digest_free_event_shows_free() -> None:
    generated_at = datetime(2026, 7, 11, 9, 0, tzinfo=UTC)
    event = _make_event(
        id=1,
        title="Free Movie Night",
        start_at=datetime(2026, 7, 15, 20, 0, tzinfo=UTC),
        created_at=generated_at,
        is_free=True,
        price=None,
    )

    out = render_digest([_scored(event)], generated_at, 7)

    line = next(line for line in out.splitlines() if line.startswith("- "))
    assert "Free" in line
    assert "$" not in line


def test_render_digest_priced_event_shows_dollar_amount_no_trailing_zeros() -> None:
    generated_at = datetime(2026, 7, 11, 9, 0, tzinfo=UTC)
    event = _make_event(
        id=1,
        title="Phoebe Bridgers",
        start_at=datetime(2026, 7, 15, 20, 0, tzinfo=UTC),
        created_at=generated_at,
        is_free=False,
        price=Decimal("78.00"),
    )

    out = render_digest([_scored(event)], generated_at, 7)

    line = next(line for line in out.splitlines() if line.startswith("- "))
    assert "$78" in line
    assert "$78.00" not in line
    assert "Free" not in line


def test_render_digest_missing_price_shows_price_tba() -> None:
    generated_at = datetime(2026, 7, 11, 9, 0, tzinfo=UTC)
    event = _make_event(
        id=1,
        title="Mystery Event",
        start_at=datetime(2026, 7, 15, 20, 0, tzinfo=UTC),
        created_at=generated_at,
        is_free=False,
        price=None,
    )

    out = render_digest([_scored(event)], generated_at, 7)

    line = next(line for line in out.splitlines() if line.startswith("- "))
    assert "price TBA" in line


def test_render_digest_link_omitted_when_external_url_is_none() -> None:
    generated_at = datetime(2026, 7, 11, 9, 0, tzinfo=UTC)
    event = _make_event(
        id=1,
        title="No Link Event",
        start_at=datetime(2026, 7, 15, 20, 0, tzinfo=UTC),
        created_at=generated_at,
        external_url=None,
    )

    out = render_digest([_scored(event)], generated_at, 7)

    line = next(line for line in out.splitlines() if line.startswith("- "))
    assert "[link]" not in line


def test_render_digest_link_present_when_external_url_set() -> None:
    generated_at = datetime(2026, 7, 11, 9, 0, tzinfo=UTC)
    event = _make_event(
        id=1,
        title="Linked Event",
        start_at=datetime(2026, 7, 15, 20, 0, tzinfo=UTC),
        created_at=generated_at,
        external_url="https://tickets.example.com/123",
    )

    out = render_digest([_scored(event)], generated_at, 7)

    line = next(line for line in out.splitlines() if line.startswith("- "))
    assert "[link](https://tickets.example.com/123)" in line


def test_render_digest_venue_falls_back_to_tba() -> None:
    generated_at = datetime(2026, 7, 11, 9, 0, tzinfo=UTC)
    event = _make_event(
        id=1,
        title="No Venue Event",
        start_at=datetime(2026, 7, 15, 20, 0, tzinfo=UTC),
        created_at=generated_at,
        venue_name=None,
    )

    out = render_digest([_scored(event)], generated_at, 7)

    line = next(line for line in out.splitlines() if line.startswith("- "))
    assert "TBA" in line


def test_render_digest_shows_up_to_two_tags() -> None:
    generated_at = datetime(2026, 7, 11, 9, 0, tzinfo=UTC)
    event = _make_event(
        id=1,
        title="Tagged Event",
        start_at=datetime(2026, 7, 15, 20, 0, tzinfo=UTC),
        created_at=generated_at,
    )

    out = render_digest(
        [_scored(event, matched_tags=["#LiveMusic", "#Indie", "#Chill"])],
        generated_at,
        7,
    )

    line = next(line for line in out.splitlines() if line.startswith("- "))
    assert "#LiveMusic" in line
    assert "#Indie" in line
    assert "#Chill" not in line


def test_render_digest_no_tags_omits_tag_segment() -> None:
    generated_at = datetime(2026, 7, 11, 9, 0, tzinfo=UTC)
    event = _make_event(
        id=1,
        title="Untagged Event",
        start_at=datetime(2026, 7, 15, 20, 0, tzinfo=UTC),
        created_at=generated_at,
        tags=[],
    )

    out = render_digest([_scored(event, matched_tags=[])], generated_at, 7)

    line = next(line for line in out.splitlines() if line.startswith("- "))
    assert line.count("_") == 0


def test_render_digest_fallback_footer_present_when_fallback_true() -> None:
    generated_at = datetime(2026, 7, 11, 9, 0, tzinfo=UTC)
    event = _make_event(
        id=1,
        title="Event",
        start_at=datetime(2026, 7, 15, 20, 0, tzinfo=UTC),
        created_at=generated_at,
    )

    out = render_digest([_scored(event)], generated_at, 7, fallback=True)

    assert "_(ranked by freshness+popularity — no user signals)_" in out


def test_render_digest_fallback_footer_absent_when_personalized() -> None:
    generated_at = datetime(2026, 7, 11, 9, 0, tzinfo=UTC)
    event = _make_event(
        id=1,
        title="Event",
        start_at=datetime(2026, 7, 15, 20, 0, tzinfo=UTC),
        created_at=generated_at,
    )

    out = render_digest([_scored(event)], generated_at, 7, fallback=False)

    assert "no user signals" not in out


# ---------------------------------------------------------------------------
# rank_without_user
# ---------------------------------------------------------------------------


def test_rank_without_user_never_takes_a_session_param() -> None:
    params = inspect.signature(rank_without_user).parameters
    assert "session" not in params


def test_rank_without_user_more_popular_ranks_first() -> None:
    now = datetime(2026, 7, 11, 9, 0, tzinfo=UTC)
    same_created_at = now - timedelta(days=3)
    popular = _make_event(
        id=1, title="Popular", start_at=now + timedelta(days=1), created_at=same_created_at
    )
    unpopular = _make_event(
        id=2, title="Unpopular", start_at=now + timedelta(days=1), created_at=same_created_at
    )

    ranked = rank_without_user(
        [unpopular, popular], {1: 10, 2: 0}, now
    )

    assert [se.event.id for se in ranked] == [1, 2]


def test_rank_without_user_newer_created_ranks_first() -> None:
    now = datetime(2026, 7, 11, 9, 0, tzinfo=UTC)
    fresh = _make_event(
        id=1,
        title="Fresh",
        start_at=now + timedelta(days=1),
        created_at=now - timedelta(hours=1),
    )
    stale = _make_event(
        id=2,
        title="Stale",
        start_at=now + timedelta(days=1),
        created_at=now - timedelta(days=30),
    )

    ranked = rank_without_user([stale, fresh], {}, now)

    assert [se.event.id for se in ranked] == [1, 2]


def test_rank_without_user_tie_break_by_start_at_then_id() -> None:
    now = datetime(2026, 7, 11, 9, 0, tzinfo=UTC)
    same_created_at = now - timedelta(hours=1)
    same_popularity = {1: 5, 2: 5, 3: 5}

    later = _make_event(
        id=1, title="Later", start_at=now + timedelta(days=2), created_at=same_created_at
    )
    sooner_higher_id = _make_event(
        id=3, title="Sooner higher id", start_at=now + timedelta(days=1), created_at=same_created_at
    )
    sooner_lower_id = _make_event(
        id=2, title="Sooner lower id", start_at=now + timedelta(days=1), created_at=same_created_at
    )

    ranked = rank_without_user(
        [later, sooner_higher_id, sooner_lower_id], same_popularity, now
    )

    # All tied on total_score (same popularity + freshness) — sooner start_at
    # wins, then lower id breaks the remaining tie.
    assert [se.event.id for se in ranked] == [2, 3, 1]


def test_rank_without_user_returns_scored_event_with_empty_matched_tags() -> None:
    now = datetime(2026, 7, 11, 9, 0, tzinfo=UTC)
    event = _make_event(
        id=1, title="Event", start_at=now + timedelta(days=1), created_at=now, tags=["#Jazz"]
    )

    ranked = rank_without_user([event], {}, now)

    assert ranked[0].matched_tags == []
    assert ranked[0].vibe_score == 0.0
