"""Export a markdown events digest for the Life OS weekly weave.

Ranks upcoming events for a user (personalized via RecommenderService when the
user has vibe signals, otherwise a freshness+popularity fallback) and writes a
short markdown digest to disk — by default into the Digital Brain vault, where
the weekly-review routine picks it up if it's fresh (see
`routines/weekly-review.md` in that repo).

Usage:
    .venv/bin/python scripts/export_digest.py [--user-id 1] [--days 7] \
        [--out ~/workspace/Matthew\\ Digital\\ Brain/reference/events-digest.md] [--top 15]

`render_digest` and `rank_without_user` are pure (no DB access) — see
tests/test_export_digest.py. All database work happens in `main()`.
"""
from __future__ import annotations

import argparse
import sys
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from pathlib import Path

from sqlalchemy import func
from sqlmodel import Session, select

from app.core.database import engine
from app.core.localtime import LOCAL_TZ
from app.models.event import Event
from app.models.user import User
from app.models.user_signal import UserSignal
from app.services.recommender import RecommenderService, ScoredEvent
from app.services.user_profile import UserProfileService

DEFAULT_OUT = str(
    Path.home() / "workspace" / "Matthew Digital Brain" / "reference" / "events-digest.md"
)
FALLBACK_NOTE = "_(ranked by freshness+popularity — no user signals)_"


def _format_price(*, is_free: bool, price: Decimal | None) -> str:
    """Render the price segment: "Free", "$X" (no trailing .00), or "price TBA"."""
    if is_free:
        return "Free"
    if price is None:
        return "price TBA"
    as_float = float(price)
    if as_float == int(as_float):
        return f"${int(as_float)}"
    return f"${as_float:.2f}"


def _format_when(start_at: datetime) -> str:
    """Render "<Ddd Mon D h:mma>" in local (SF) wall-clock time."""
    local = start_at.astimezone(LOCAL_TZ)
    date_part = local.strftime("%a %b %-d")
    time_part = local.strftime("%-I:%M%p").lower()
    return f"{date_part} {time_part}"


def _render_event_line(scored_event: ScoredEvent) -> str:
    event = scored_event.event
    segments = [f"**{event.title}** — {_format_when(event.start_at)}"]
    segments.append(event.venue_name or "TBA")
    segments.append(_format_price(is_free=bool(event.is_free), price=event.price))
    if event.external_url:
        segments.append(f"[link]({event.external_url})")
    tags = scored_event.matched_tags or list(event.tags or [])
    if tags:
        segments.append(f"_{' '.join(tags[:2])}_")
    return "- " + " · ".join(segments)


def render_digest(
    scored: list[ScoredEvent],
    generated_at: datetime,
    window_days: int,
    *,
    top: int = 15,
    fallback: bool = False,
) -> str:
    """Pure: render a markdown digest from an already-ranked list of ScoredEvent.

    Does not touch the database — callers pass in whatever RecommenderService
    (or rank_without_user) already produced.
    """
    lines = [
        f"# Events digest — {generated_at.date().isoformat()}",
        f"_Window: next {window_days} days · generated by truth-of-fun · "
        f"regenerate: make digest_",
        "",
    ]

    top_events = scored[:top]
    if not top_events:
        lines.append("_No events found in this window._")
    else:
        lines.extend(_render_event_line(se) for se in top_events)

    if fallback:
        lines.append("")
        lines.append(FALLBACK_NOTE)

    return "\n".join(lines) + "\n"


def rank_without_user(
    events: list[Event],
    popularity_counts: dict[int, int],
    now: datetime,
) -> list[ScoredEvent]:
    """Pure: rank events by freshness+popularity only, no user/session involved.

    Reuses RecommenderService's freshness/popularity component formulas (both
    0-100, equally weighted) so the fallback ranking stays consistent with the
    personalized one. Deterministic tie-break: start_at ascending, then id
    ascending (so soonest / lowest-id events win ties).
    """
    scored: list[ScoredEvent] = []
    for event in events:
        popularity_score = RecommenderService._popularity_score(
            popularity_counts.get(int(event.id or 0), 0)
        )
        freshness_score = RecommenderService._freshness_score(event.created_at, now=now)
        total_score = popularity_score + freshness_score
        scored.append(
            ScoredEvent(
                event=event,
                total_score=total_score,
                vibe_score=0.0,
                popularity_score=popularity_score,
                freshness_score=freshness_score,
                matched_tags=[],
            )
        )

    scored.sort(key=lambda se: (-se.total_score, se.event.start_at, se.event.id or 0))
    return scored


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--user-id", type=int, default=1, help="User to personalize for")
    parser.add_argument("--days", type=int, default=7, help="Window size in days")
    parser.add_argument("--out", type=str, default=DEFAULT_OUT, help="Output markdown path")
    parser.add_argument("--top", type=int, default=15, help="Max events to include")
    args = parser.parse_args()

    now = datetime.now(timezone.utc)
    window_end = now + timedelta(days=args.days)

    user_profile_service = UserProfileService()
    recommender_service = RecommenderService()

    with Session(engine) as session:
        upcoming_events = session.exec(
            select(Event)
            .where(Event.start_at >= now, Event.start_at <= window_end)
            .order_by(Event.start_at.asc())
        ).all()

        pop_rows = session.exec(
            select(UserSignal.event_id, func.count(func.distinct(UserSignal.user_id)))
            .where(
                UserSignal.event_id.isnot(None),
                UserSignal.signal_type.in_(["save", "click", "external_ticket_click"]),
            )
            .group_by(UserSignal.event_id)
        ).all()
        popularity_counts = {int(eid): int(cnt) for eid, cnt in pop_rows if eid is not None}

        user = session.get(User, args.user_id)
        fallback = False
        if user is None:
            print(f"[digest] user_id={args.user_id} not found — fallback mode (freshness+popularity)")
            scored = rank_without_user(upcoming_events, popularity_counts, now)
            fallback = True
        else:
            profile_scores = user_profile_service.compute_vibe_scores_for_user(
                session=session, user_id=args.user_id, now=now
            )
            preferred_vibes = [v for v in (user.preferred_vibes or []) if isinstance(v, str)]
            if not preferred_vibes and not profile_scores:
                print(
                    f"[digest] user_id={args.user_id} has no vibe signals — "
                    "fallback mode (freshness+popularity)"
                )
                scored = rank_without_user(upcoming_events, popularity_counts, now)
                fallback = True
            else:
                print(f"[digest] user_id={args.user_id} — personalized mode")
                scored = recommender_service.score_events(
                    events=upcoming_events,
                    user=user,
                    user_vibe_scores=profile_scores,
                    popularity_counts=popularity_counts,
                )

    digest_md = render_digest(
        scored, now, args.days, top=args.top, fallback=fallback
    )

    out_path = Path(args.out).expanduser()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(digest_md)
    print(f"[digest] wrote {min(len(scored), args.top)} events -> {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
